classDiagram

    class SCR_BaseLinkedStorageLogic {
    }

    class SCR_GetLinkedStorageChildren {
        - storage: BaseInventoryStorageComponent
    }

    class SCR_MirrorLinkStorageToParent {
    }

    class SCR_SetLinkedStorageToParent {
    }

